import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import {validateDraft,exportPrototype,importPrototype,reviewPrototype,contextExamples} from '../src/lib/prototype.mjs';
import {readSettings,inspectProposal,revisionConflict} from '../src/lib/admin-local.mjs';
const atlas=JSON.parse(fs.readFileSync('src/data/atlas.json','utf8'));
const refs={skills:atlas.skills,packages:atlas.packages,cards:atlas.wh.cards.map(c=>({...c,id:String(c.id),section:c.family,name:c.mechanism_name}))};
const draft=()=>({title:'ร่วมกันสร้างเส้นทาง',packageId:null,skills:['cooperation'],players:4,minutes:30,context:'ผู้เรียนสี่คน ใช้สีและข้อความร่วมกัน',core:{Conflict:'2',Order:'5',Reward:'16',Ending:'9'},taste:['22'],locked:{'22':true},roles:'แบ่งข้อมูลคนละส่วน',turns:'ผลัดกันเลือกหนึ่งการ์ด',objective:'สร้างเส้นทางร่วมกัน',ending:'จบสามรอบ',cardCount:30,rules:'ผู้เล่นเลือกคนละส่วน อธิบายเหตุผลหลังรอบ',debrief:'ส่วนของใครช่วยการตัดสินใจเพื่อน',analysisReview:true});
test('prototype save/export/import roundtrip preserves rules, locks and review boundary',()=>{const d=draft(),encoded=JSON.stringify(exportPrototype(d,refs)),got=importPrototype(encoded,refs);assert.deepEqual(got,d);assert.equal(JSON.parse(encoded).scores,null);assert.equal(reviewPrototype(got,refs).ready,true)});
test('legacy prototype migrates; malformed IDs, bounds, score claims and nested keys fail closed',()=>{const d=draft();assert.deepEqual(importPrototype(JSON.stringify({version:1,...d,scores:null}),refs),d);for(const bad of [{...d,players:0},{...d,core:{...d.core,Conflict:'22'}},{...d,taste:['999']},{...d,locked:{'30':true}}])assert.throws(()=>validateDraft(bad,refs));assert.throws(()=>importPrototype(JSON.stringify({...exportPrototype(d,refs),scores:{cooperation:9}}),refs));assert.throws(()=>importPrototype('{"version":2,"draft":{"__proto__":{}}}',refs));assert.throws(()=>importPrototype('x'.repeat(128001),refs));assert.deepEqual(d,draft())});
test('review identifies missing playable rules and coherence questions without producing scores',()=>{const d=draft();d.core.Conflict='1';assert.match(reviewPrototype(d,refs).warnings.join(' '),/Cooperation/);d.ending='';d.rules='';assert.equal(reviewPrototype(d,refs).ready,false);assert.ok(reviewPrototype(d,refs).errors.some(x=>x.includes('จบเกม')));assert.equal('scores' in reviewPrototype(d,refs),false)});
test('game examples obey explicit player counts and unknown context fails closed',()=>{const list=[{status:'supported',game_id:'lunar',applicable_player_counts:[4]},{status:'conditional',game_id:'other',applicable_player_counts:[3]},{status:'supported',game_id:'unresolved'}];assert.deepEqual(contextExamples(list,2),[]);assert.deepEqual(contextExamples(list,4).map(x=>x.game_id),['lunar'])});
const hash=async x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
test('sourced proposal export/import checks dataset and record revisions with no source mutation',async()=>{const old=atlas.catalogue.records[0],before=JSON.stringify(old);const p={collection:'games',record_id:old.game_id,base_dataset_revision:atlas.digest,base_record_revision:old.record_revision_sha256??await hash(old),changes:{...old,name:old.name+' — proposed'},sources:[{url:'https://example.org/rules',locator:'page 2',read_scope:'turn sequence'}]};const r=await inspectProposal(JSON.parse(JSON.stringify(p)),atlas,hash);assert.equal(r.isNew,false);assert.equal(r.status,'revision-compatible-awaiting-canonical-review');assert.equal(JSON.stringify(old),before);await assert.rejects(()=>inspectProposal({...p,base_dataset_revision:'0'.repeat(64)},atlas,hash));await assert.rejects(()=>inspectProposal({...p,base_record_revision:'1'.repeat(64)},atlas,hash));await assert.rejects(()=>inspectProposal({...p,sources:[]},atlas,hash));await assert.rejects(()=>inspectProposal({...p,changes:JSON.parse('{"nested":{"__proto__":{}}}')},atlas,hash))});
test('settings roundtrip preserves draft and fails closed on revision conflicts including unknown base',()=>{const site=JSON.parse(fs.readFileSync('src/data/site.json','utf8')),sha='a'.repeat(40);assert.deepEqual(readSettings(JSON.stringify({site,base_sha:sha})),{site,base_sha:sha});assert.equal(revisionConflict({dirty:true,baseSha:sha,remoteSha:'b'.repeat(40)}),true);assert.equal(revisionConflict({dirty:true,baseSha:'',remoteSha:sha}),true);assert.equal(revisionConflict({dirty:false,baseSha:'',remoteSha:sha}),false);assert.throws(()=>readSettings(JSON.stringify({site:{...site,theme:{...site.theme,radius:99}},base_sha:sha}))) });

import {setupReport} from '../auth-service/scripts/check-setup.mjs';
test('setup checker reports readiness without leaking values',()=>{const fake={GITHUB_CLIENT_ID:'dummy-id',GITHUB_CLIENT_SECRET:'dummy-secret',SESSION_SECRET:'x'.repeat(32),AUTH_ORIGIN:'https://example-auth.vercel.app'};const r=setupReport(fake);assert.equal(r.configured,true);assert.equal(JSON.stringify(r).includes('dummy-secret'),false);assert.equal(setupReport({...fake,SESSION_SECRET:'short'}).configured,false);assert.equal(setupReport({}).configured,false)});

test('settings reject rules before activity and unsafe nested keys',()=>{const site=JSON.parse(fs.readFileSync('src/data/site.json','utf8'));site.builder.stepOrder=['skills','rules','activity','review'];assert.throws(()=>readSettings(JSON.stringify({site,base_sha:''})),/dependency/);site.builder.stepOrder=['skills','activity','rules','review'];site.pages.catalogue.extra=JSON.parse('{"__proto__":{}}');assert.throws(()=>readSettings(JSON.stringify({site,base_sha:''})),/nested/)});
