import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {seal,unseal,cors,requireEditor} from '../auth-service/lib/security.mjs';
import {validSite,validProposal} from '../auth-service/lib/validation.mjs';
const secret='a'.repeat(64),future=()=>({kind:'session',access_token:'test-runtime-only',exp:Date.now()+10000});
test('encrypted sessions reject tampering, expiry and weak configuration',()=>{const token=seal(future(),secret);assert.deepEqual(unseal(token,secret).access_token,'test-runtime-only');assert.throws(()=>unseal(token.slice(0,12)+(token[12]==='a'?'b':'a')+token.slice(13),secret));assert.throws(()=>unseal(seal({...future(),exp:1},secret),secret));assert.throws(()=>seal(future(),'short'));assert.ok(!token.includes('test-runtime-only'));});
test('cross-origin requests fail closed',()=>{let status;const res={setHeader(){},status(n){status=n;return this},json(){},end(){}};assert.equal(cors({headers:{origin:'https://attacker.example'},method:'POST'},res),false);assert.equal(status,403);});
test('every admin request requires a session before reaching GitHub',async()=>{await assert.rejects(()=>requireEditor({headers:{}}),/Login required/)});
test('valid configuration preserves dependency and rejects invalid values',()=>{const site=JSON.parse(fs.readFileSync('src/data/site.json'));assert.equal(validSite(site),site);const c=structuredClone(site);c.builder.stepOrder=['activity','skills','rules','review'];assert.throws(()=>validSite(c),/dependency/);const d=structuredClone(site);d.theme.primary='url(javascript:alert(1))';assert.throws(()=>validSite(d),/colour/);});
test('knowledge changes require revision and source locators',()=>{const p={collection:'games',record_id:'test-game',base_dataset_revision:'a'.repeat(64),base_record_revision:null,changes:{name:'Test'},sources:[{url:'https://example.com/rules',locator:'page 2',read_scope:'turn rules'}]};assert.equal(validProposal(p),p);assert.throws(()=>validProposal({...p,sources:[]}),/source/);assert.throws(()=>validProposal({...p,base_dataset_revision:''}),/revision/)});
