import crypto from 'node:crypto';
import {cors,requireEditor,github,REPO} from '../lib/security.mjs';
import {validSite,validProposal} from '../lib/validation.mjs';
const SITE='src/data/site.json',ATLAS='src/data/atlas.json';
async function content(path,token,ref='main'){const file=await github(`/repos/${REPO}/contents/${path}?ref=${encodeURIComponent(ref)}`,token);let body=file.content;if(!body){const blob=await github(`/repos/${REPO}/git/blobs/${file.sha}`,token);body=blob.content;}return {sha:file.sha,data:JSON.parse(Buffer.from(body,'base64').toString('utf8'))};}
const hash=r=>crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex');
function record(atlas,p){const map={games:atlas.catalogue.records??atlas.catalogue.games,skills:atlas.activities.skills,'wizard-hat':atlas.wh.cards,packages:atlas.packages,sources:atlas.activities.sources};return (map[p.collection]??[]).find(r=>String(r.game_id??r.skill_id??r.id??r.source_id)===p.record_id);}
async function saveSite(s,sha,token,message){validSite(s);if(!/^[a-f0-9]{40}$/.test(sha??''))throw Error('A base file revision is required');return github(`/repos/${REPO}/contents/${SITE}`,token,{method:'PUT',body:JSON.stringify({branch:'main',message,sha,content:Buffer.from(JSON.stringify(s,null,2)+'\n').toString('base64')})});}
export default async function handler(req,res){if(!cors(req,res))return;try{const s=await requireEditor(req),token=s.access_token;if(req.method==='GET'){const action=req.query.action??'content';if(action==='content'){const f=await content(SITE,token);return res.status(200).json({...f,login:s.login});}if(action==='history'){const list=await github(`/repos/${REPO}/commits?path=${SITE}&per_page=20`,token);return res.status(200).json({commits:list.map(c=>({sha:c.sha,message:c.commit.message,date:c.commit.author.date,url:c.html_url}))});}if(action==='status'){const r=await github(`/repos/${REPO}/actions/workflows/pages.yml/runs?per_page=10`,token);return res.status(200).json({runs:r.workflow_runs.map(w=>({id:w.id,sha:w.head_sha,status:w.status,conclusion:w.conclusion,url:w.html_url,created_at:w.created_at}))});}throw Error('Unknown read action');}
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const body=typeof req.body==='string'?JSON.parse(req.body):req.body;if(body.action==='save'){const r=await saveSite(body.site,body.base_sha,token,`Publish website settings by ${s.login}`);return res.status(200).json({sha:r.content.sha,commit:r.commit.sha,url:r.commit.html_url,state:'committed-deployment-pending'});}if(body.action==='revert'){if(!/^[a-f0-9]{40}$/.test(body.revision??''))throw Error('Invalid target revision');const old=await content(SITE,token,body.revision);const r=await saveSite(old.data,body.base_sha,token,`Restore website settings from ${body.revision.slice(0,7)} by ${s.login}`);return res.status(200).json({sha:r.content.sha,commit:r.commit.sha,url:r.commit.html_url,state:'reverted-deployment-pending'});}
 if(body.action==='proposal'){const p=validProposal(body.proposal),atlas=(await content(ATLAS,token)).data;if(p.base_dataset_revision!==atlas.digest){return res.status(409).json({error:'Knowledge source export has changed. Reload the latest data before proposing changes.',current_revision:atlas.digest});}const old=record(atlas,p),revision=old?(old.record_revision_sha256??hash(old)):null;if(p.base_record_revision!==revision)return res.status(409).json({error:'This record has changed. Reload before proposing changes.',current_revision:revision});const proposed={...p,proposal_id:crypto.randomUUID(),schema_version:1,created_at:new Date().toISOString(),created_by:s.login,status:'pending-canonical-review',source_owner:'local-canonical-KB',web_facts_published:false};const path=`src/data/proposals/${proposed.proposal_id}.json`;const r=await github(`/repos/${REPO}/contents/${path}`,token,{method:'PUT',body:JSON.stringify({branch:'main',message:`Sourced ${p.collection} proposal by ${s.login}`,content:Buffer.from(JSON.stringify(proposed,null,2)+'\n').toString('base64')})});return res.status(200).json({commit:r.commit.sha,url:r.commit.html_url,proposal:proposed,state:'proposal-saved-awaiting-canonical-merge'});}throw Error('Unknown write action');
 }catch(e){const status=e.status===409?409:e.status===401?401:e.status===403?403:/Login required|Session expired|Invalid session/.test(e.message)?401:400;return res.status(status).json({error:e.message??'Operation failed'});}}
