import crypto from 'node:crypto';
export const REPO='wollab/learning-game-atlas';
export const SITE_ORIGIN='https://wollab.github.io';
export const ADMIN_URL='https://wollab.github.io/learning-game-atlas/admin/';
export function seal(data,secret=process.env.SESSION_SECRET){if(!secret||secret.length<32)throw Error('Server session secret is not configured');const key=crypto.createHash('sha256').update(secret).digest(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(JSON.stringify(data)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url');}
export function unseal(token,secret=process.env.SESSION_SECRET){if(!secret||secret.length<32)throw Error('Server session secret is not configured');const b=Buffer.from(token??'','base64url');if(b.length<29)throw Error('Invalid session');const decipher=crypto.createDecipheriv('aes-256-gcm',crypto.createHash('sha256').update(secret).digest(),b.subarray(0,12));decipher.setAuthTag(b.subarray(12,28));const d=JSON.parse(Buffer.concat([decipher.update(b.subarray(28)),decipher.final()]).toString());if(!d.exp||d.exp<Date.now())throw Error('Session expired');return d;}
export function cors(req,res){const origin=req.headers.origin;res.setHeader('Vary','Origin');if(origin&&origin!==SITE_ORIGIN){res.status(403).json({error:'Origin is not allowed'});return false;}if(origin)res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.method==='OPTIONS'){res.status(204).end();return false;}return true;}
export function session(req){const h=req.headers.authorization??'';if(!h.startsWith('Bearer '))throw Error('Login required');const d=unseal(h.slice(7));if(d.kind!=='session'||!d.access_token)throw Error('Login required');return d;}
export async function github(path,token,options={}){const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'Learning-Game-Atlas',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});const json=await r.json().catch(()=>({}));if(!r.ok){const e=Error(json.message??`GitHub request failed (${r.status})`);e.status=r.status;throw e;}return json;}
export async function requireEditor(req){const s=session(req),repo=await github(`/repos/${REPO}`,s.access_token);if(!repo.permissions?.push){const e=Error('Your GitHub account does not have write permission to this repository');e.status=403;throw e;}return s;}
export const random=()=>crypto.randomBytes(32).toString('base64url');
export const cookie=(req,name)=>decodeURIComponent((req.headers.cookie??'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)??'');
export function clearOAuth(res){res.setHeader('Set-Cookie','atlas_oauth=; Path=/api; HttpOnly; Secure; SameSite=Lax; Max-Age=0');}
