import '../atlas-refresh.css';
import {useState,useEffect,useRef,lazy,Suspense} from 'react';
import {BookOpen,Search,Layers,Lightbulb,WandSparkles,Library,Settings,Menu,Sparkle,Target,PanelLeftClose,PanelLeftOpen,LayoutGrid,List,ArrowLeftRight,ArrowRight,X,Users,Clock,Brain,Waypoints,Award,Eye,EyeOff,Hourglass} from 'lucide-react';
import {games,skills,cards,packages,site,url,base,skillName,searchGames,supported,isGameInResearch,relatedGames,cleanText,groups,groupNames,groupColors,skillExamples,packagesForSkill} from '../lib/model';
import type {Row} from '../lib/model';
import {Sources,HatChip,Pizza,SkillFlow,EvidenceLabel} from './Shared';
import Builder from './Builder';
import Catalogue from './Catalogue';
import {GameDetail,Compare,Skills} from './GameViews';
import BGGInfo from './BGGInfo';
import {GameCover,AwardBadges,SelectionPopover} from './GameMedia';
const Admin=lazy(()=>import('./Admin'));
const nav=[['catalogue','คลังเกม',LayoutGrid],['skills','12 ทักษะ',Target],['wizard-hat','Wizard Hat',Sparkle],['builder','สร้างต้นแบบ',WandSparkles],['methodology','วิธีอ่านข้อมูล',BookOpen],['sources','แหล่งอ้างอิง',Search]] as const;
export default function App({route}:{route:string}){
 const [ready,setReady]=useState(false),[params,setParams]=useState<URLSearchParams>(new URLSearchParams()),[collapsed,setCollapsed]=useState(false);const drawer=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setParams(new URLSearchParams(location.search));try{setCollapsed(localStorage.getItem('atlas-rail')==='1')}catch{}setReady(true);document.documentElement.dataset.ready='true'},[]);
 const page=site.pages[route]??{title:route==='game'?'รายละเอียดเกม':route==='compare'?'เปรียบเทียบเกม':'ทักษะและกติกา',intro:''};
 const navigation=nav.map(([r,label,Icon])=><a key={r} href={url(r)} aria-label={label} title={label} aria-current={route===r?'page':undefined}><Icon/><span>{label}</span></a>);
 return <div data-route={route} className={`app ${collapsed?'collapsed':''}`} style={{'--primary':site.theme.primary,'--accent':site.theme.accent,'--background':site.theme.background,'--ink':site.theme.ink,'--radius':`${site.theme.radius}px`,'--heading-font':site.theme.headingFont,'--body-font':site.theme.bodyFont} as any}><a className="skip" href="#main">ข้ามไปเนื้อหา</a><header className="topbar"><button className="mobile-menu icon-button" aria-label="เปิดเมนู" onClick={()=>drawer.current?.showModal()}><Menu/></button><a href={url('catalogue')} className="brand"><img className="brand-logo" src={base+'/assets/brand/wol-logo.png'} alt="Wizards of Learning" width="44" height="44"/>Learning Game Atlas</a></header><aside className="rail"><button className="rail-toggle icon-button" aria-label={collapsed?'ขยายเมนู':'ย่อเมนู'} onClick={()=>{setCollapsed(!collapsed);try{localStorage.setItem('atlas-rail',!collapsed?'1':'0')}catch{}}}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}<span>{collapsed?'':'ย่อเมนู'}</span></button><nav>{navigation}</nav><a className="admin-link" href={url('admin')}><Settings/><span>จัดการเว็บไซต์</span></a></aside><dialog className="drawer" ref={drawer}><button className="icon-button" aria-label="ปิดเมนู" onClick={()=>drawer.current?.close()}><X/></button><nav>{navigation}</nav><a href={url('admin')}>จัดการเว็บไซต์</a></dialog><main id="main">{route!=='game'&&<div className="page-heading"><h1>{page.title}</h1>{page.intro&&<p>{page.intro}</p>}</div>}{route==='catalogue'&&<Catalogue/>}{route==='game'&&ready&&<GameDetail id={params.get('id')??'high-society'}/ >}{route==='compare'&&ready&&<Compare ids={(params.get('ids')??'').split(',')}/ >}{['skills','skill'].includes(route)&&<Skills id={ready?params.get('id'):null}/ >}{route==='wizard-hat'&&<HatLibrary id={ready?params.get('id'):null}/ >}{route==='builder'&&ready&&<Builder params={params}/ >}{route==='admin'&&ready&&<Suspense fallback={<p>กำลังเปิดหน้าจัดการเว็บไซต์…</p>}><Admin/></Suspense>}{route==='methodology'&&<Methodology/>}{route==='sources'&&<SourceLibrary/>}<footer><p>Learning Game Atlas · Wizards of Learning</p><a href="https://wollab.github.io/WizardHat_LearningOutcome/" target="_blank" rel="noreferrer">Wizard Hat — Learning Outcome</a></footer></main></div>
}
function HatLibrary({id}:{id:string|null}){const [section,setSection]=useState(''),[q,setQ]=useState(''),[view,setView]=useState('shelf');const card=cards.find(c=>c.id===id);if(card)return <><a href={url('wizard-hat')}>กลับคลัง Wizard Hat</a><div className="hat-detail"><img src={`${base}/${card.asset}`} width="408" height="576" alt={card.name}/><section><p><Layers size={18}/>{card.section} · {card.category}</p><h2>{card.name}</h2><p>{card.description??card.explanation}</p><p>{card.how_it_works??card.usage}</p><p>ตัวอย่างเกม: {Array.isArray(card.examples)?card.examples.join(', '):card.examples}</p><Sources sources={card.sources}/><a className="button" href={url('builder',{card:card.id})}><WandSparkles/>ใช้กลไกนี้สร้างต้นแบบ</a></section></div></>;const shown=cards.filter(c=>(!section||c.section===section)&&`${c.name} ${c.thai} ${c.category}`.toLowerCase().includes(q.toLowerCase()));return <><div className="search-row"><label className="search-box"><Search/><input aria-label="ค้นหา Wizard Hat" value={q} onChange={e=>setQ(e.target.value)} placeholder="ชื่อกลไกหรือหมวด"/></label><select aria-label="CORE หรือ TASTE" value={section} onChange={e=>setSection(e.target.value)}><option value="">ทั้งหมด 50 ใบ</option><option>CORE</option><option>TASTE</option></select><div className="view-toggle"><button aria-pressed={view==='shelf'} onClick={()=>setView('shelf')}><LayoutGrid/>การ์ด</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}><List/>รายการ</button></div></div>{['CORE','TASTE'].filter(x=>!section||x===section).map(sec=><section className="hat-section" key={sec}><h2><Sparkle/>{sec==='CORE'?'CORE — โครงสร้างหลัก':'TASTE — กลไกเสริมรสชาติ'}</h2>{[...new Set(shown.filter(c=>c.section===sec).map(c=>c.category))].map(category=><section className="hat-category" key={category}><h3><Layers/>{category}</h3><div className={view==='shelf'?'hat-shelf':'hat-list'}>{shown.filter(c=>c.section===sec&&c.category===category).map(c=><a href={url('wizard-hat',{id:c.id})} key={c.id}><img src={`${base}/${c.asset}`} loading="lazy" width="408" height="576" alt={view==='shelf'?c.name:''}/><span>{c.name}</span>{view==='list'&&<ArrowRight size={18}/>}</a>)}</div></section>)}</section>)}</>}
function Methodology(){return <div className="reading"><h2>ทักษะเริ่มจากสิ่งที่ผู้เล่นทำ</h2><p>อ่านกิจกรรมสร้างการเรียนรู้และกติกาที่เรียกพฤติกรรมนั้น ก่อนเชื่อมกับ Wizard Hat การมีโอกาสในเกมยังไม่ยืนยันว่าผู้เล่นพัฒนา หรือถ่ายโอนทักษะไปนอกเกม</p><h2>อ่านสีและหลักฐาน</h2><p>วงกลมแบ่ง 12 ส่วนขนาดเท่ากัน สีประจำกลุ่มแสดงส่วนที่มีข้อมูลกติกาสนับสนุน ลายเส้นแสดงเงื่อนไข สีอ่อนประจำหมวดแสดงข้อมูลที่ยังไม่เพียงพอ ไม่มีขนาดหรือคะแนนแทนความสามารถ</p><h2>ดูจำนวนผู้เล่นและรุ่นเกม</h2><p>ข้อวิเคราะห์ขึ้นอยู่กับกติกา รุ่น จำนวนผู้เล่น และบริบทที่ระบุ โหมดต่างกันอาจสร้างพฤติกรรมต่างกัน</p><h2>เวลาและความนิยม</h2><p>เวลาแสดงค่าที่ผู้ผลิตระบุ เวลาสอน เตรียม เล่น และสรุปผลที่สังเกตจริงเก็บแยกกัน อันดับและคะแนน BGG ที่ยังไม่ยืนยันจะแสดงว่ายังไม่ทราบ</p><h2>ต้นแบบที่ปรับเอง</h2><p>เมื่อเปลี่ยนกติกา ข้อวิเคราะห์ทักษะเดิมต้องตรวจใหม่ ใช้ต้นแบบเพื่อทดลองและเก็บสิ่งที่ผู้เล่นทำจริง</p><a href="https://wollab.github.io/WizardHat_LearningOutcome/">ที่มาของกรอบ Wizard Hat — Learning Outcome</a></div>}
function SourceLibrary(){const sources=[...new Map(games.flatMap(g=>g.sources).map((s:Row)=>[s.url,s])).values()];return <div className="source-library">{sources.map((s:Row)=><article className="panel" key={s.url}><Sources sources={[s]}/><p>{s.read_scope}</p><p className="muted">{s.supports}</p></article>)}</div>}
