import {packages,skills,data,games,url,skillName,reviewedBridges,cardName,cards} from '../lib/model';
import type {Row} from '../lib/model';
import {HatChip,Sources} from './Shared';
import BuilderActivity from './BuilderActivity';
import {GameCover} from './GameMedia';
export function blankBinding(id:string){const a=skills.find(s=>s.id===id)?.activity?.wol_activity;return {skill_id:id,activity:a?.action_th??'',rule:'',observable:a?.observable_behaviour_th??'',counter_signal:a?.counter_signal_th??'',debrief:a?.debrief_question_th??'',origin:'WoL activity proposal; user rule needs review',source_bridge_ids:[]}}
export default function BuilderBindings({draft,onBindings,onPackage}:{draft:Row,onBindings:(b:Row[])=>void,onPackage:(p:Row)=>void}){
 const candidates=packages.filter(p=>p.skills.some((id:string)=>draft.skills.includes(id)));
 const update=(id:string,key:string,value:string)=>onBindings(draft.skills.map((sid:string)=>{const b=draft.bindings?.find((b:Row)=>b.skill_id===sid)??blankBinding(sid);return sid===id?{...b,[key]:value,origin:'User adapted WoL hypothesis; review required'}:b}));
 return <><h3>เลือกชุดกลไกเป็นจุดเริ่ม</h3><div className="package-grid package-choice">{candidates.map(p=><article className="panel" key={p.id}><h3>{p.name}</h3><p>{p.activity_th}</p><div className="chips">{p.cards.map((id:number)=><HatChip key={id} id={id}/>)}</div><details className="mechanism-reasons"><summary>ทำไมเลือกกลไกเหล่านี้ — CORE / TASTE</summary>{p.mechanism_rationales.map((r:Row)=><p key={r.card_no}><strong>{cards.find(c=>c.id===String(r.card_no))?.section} · {cardName(r.card_no)}</strong><br/>{r.explanation_th}</p>)}</details><p>{p.allowed_players.join(', ')} คน · เป้าหมายเวลา {p.playtest.duration_target_minutes} นาที (ยังไม่จับเวลาจริง)</p><p className="reference-note">{p.limitations_th}</p>{draft.skills.some((id:string)=>!p.skills.includes(id))&&<p className="condition-note">ชุดนี้ยังไม่ครอบคลุม: {draft.skills.filter((id:string)=>!p.skills.includes(id)).map(skillName).join(', ')}</p>}<button className={draft.packageId===p.id?'primary':''} onClick={()=>onPackage(p)}>{draft.packageId===p.id?'ใช้ชุดนี้อยู่':'ใช้ชุดนี้'}</button></article>)}</div><h3>ทางเชื่อมของต้นแบบ — ปรับให้ตรงกับกิจกรรมจริง</h3>{draft.skills.map((id:string)=>{const b=draft.bindings?.find((b:Row)=>b.skill_id===id)??blankBinding(id);const sources=b.source_bridge_ids.map((bid:string)=>reviewedBridges.find((r:Row)=>r.bridge_id===bid)).filter(Boolean);return <article className="prototype-chain" key={id}><h4>{skillName(id)}</h4><details className="learning-guidance"><summary>คำแนะนำในการออกแบบกิจกรรมสร้างการเรียนรู้</summary><BuilderActivity skillId={id} players={draft.players}/></details><div className="activity-editor">{[['activity','ผู้เล่นต้องทำอะไร'],['rule','กติกาข้อใดทำให้กิจกรรมนี้เกิด'],['observable','พฤติกรรมหรือเหตุการณ์ที่จะสังเกต'],['counter_signal','อะไรที่เกิดขึ้นแล้วแต่ยังไม่นับ'],['debrief','คำถามหลังเล่น']].map(([key,label])=><label key={key}>{label}<textarea aria-label={label} value={b[key]} onChange={e=>update(id,key,e.target.value)}/></label>)}</div>{sources.map((r:Row)=><div className="reference-note builder-example" key={r.bridge_id}>{games.find(g=>g.id===r.game_id)&&<GameCover game={games.find(g=>g.id===r.game_id)!}/>}<a href={url('game',{id:r.game_id})}>{data.bridges.games.find((g:Row)=>g.game_id===r.game_id)?.name??r.game_id}</a> · {r.applicable_player_counts?.join(', ')} คน · {r.status==='conditional'?'มีเงื่อนไข':'มีกติการองรับ'}{!r.applicable_player_counts?.includes(draft.players)&&<p className="condition-note">ตัวอย่างนี้ไม่ตรงจำนวน {draft.players} คนที่เลือก ใช้ศึกษาความต่างของบริบท ต้องทบทวนก่อนนำมาอ้างกับต้นแบบ</p>}<p>{r.conditions_th}</p><Sources sources={[r.rule_evidence]}/></div>)}<p className="reference-note">กติกาที่ปรับเป็นสมมติฐานของต้นแบบใหม่ หลักฐานเกมอ้างอิงไม่รับรองผลของต้นแบบนี้</p></article>})}</>;
}
