import {useState,useEffect} from 'react';
import {Lock,Unlock,Download,Save,ArrowRight,ArrowLeft,Shuffle} from 'lucide-react';
import {skills,cards,packages,skillName,cardName,activityFor,site,cleanText} from '../lib/model';
import type {Row} from '../lib/model';
import BuilderActivity from './BuilderActivity';
import TastePicker from './TastePicker';
const KEY='atlas-builder-v1';
function initial(params:URLSearchParams){const p=packages.find(p=>p.id===params.get('package'));return {title:p?.name??'ต้นแบบเกมของฉัน',packageId:p?.id??null,skills:p?.skills??(params.get('skills')?.split(',').filter(id=>skills.some(s=>s.id===id))??[]),players:site.builder.defaults.players,minutes:site.builder.defaults.minutes,context:'',core:Object.fromEntries((p?.cards?.map(String)??(params.get('card')?[params.get('card')]:[])).map((id:string)=>cards.find(c=>c.id===id)).filter((c:Row|undefined)=>c?.section==='CORE').map((c:Row)=>[c.category,c.id])) as Record<string,string>,taste:(p?.cards?.map(String)??(params.get('card')?[params.get('card')]:[])).filter((id:string)=>cards.find(c=>c.id===id)?.section==='TASTE'),locked:{} as Record<string,boolean>,roles:'',turns:site.builder.defaults.turns,objective:'',ending:'',cardCount:site.builder.defaults.cardCount,rules:p?.rule_proposal??'',debrief:p?.observation??'',analysisReview:false};}
export default function Builder({params}:{params:URLSearchParams}){const [draft,setDraft]=useState<Row>(()=>initial(params)),[step,setStep]=useState(0),[status,setStatus]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{if(!params.get('package')&&!params.get('skills')&&!params.get('card'))try{const stored=JSON.parse(localStorage.getItem(KEY)??'null');if(stored?.version===1)setDraft(stored.draft)}catch{setStatus('อ่านต้นแบบที่เก็บในเครื่องไม่ได้')}} ,[]);
 const set=(field:string,value:any,changesRules=false)=>{setDraft(d=>({...d,[field]:value,analysisReview:changesRules||d.analysisReview}));setSaved(false)};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({version:1,draft,updated:new Date().toISOString()}));setSaved(true);setStatus('บันทึกต้นแบบในอุปกรณ์นี้แล้ว')}catch{setStatus('บันทึกในอุปกรณ์ไม่ได้ ใช้ส่งออกไฟล์เพื่อเก็บต้นแบบ')}};
 const exportFile=()=>{const blob=new Blob([JSON.stringify({version:1,...draft,review_status:'needs-review',scores:null},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='learning-game-prototype.json';a.click();URL.revokeObjectURL(a.href)};
 const order=site.builder.stepOrder;const current=order[step];const canNext=draft.skills.length>0;
 const reroll=()=>{const taste=cards.filter(c=>c.section==='TASTE');set('taste',[...draft.taste.filter((id:string)=>draft.locked[id]),...taste.filter(c=>!draft.locked[c.id]).sort(()=>Math.random()-.5).slice(0,Math.max(0,3-draft.taste.filter((id:string)=>draft.locked[id]).length)).map(c=>c.id)],true)};
 return <><div className="builder-steps" aria-label="ขั้นตอนสร้างต้นแบบ">{order.map((s:string,i:number)=><button key={s} aria-current={step===i?'step':undefined} disabled={i>step&&!canNext} onClick={()=>setStep(i)}><b>{i+1}</b>{({skills:'ทักษะและผู้เล่น',activity:'กิจกรรมการเรียนรู้',rules:'ปรับกติกา',review:'ตรวจและบันทึก'} as Row)[s]}</button>)}</div><section className="builder panel">
 {current==='skills'&&<><h2>เลือกทักษะและบริบทผู้เล่น</h2><div className="skill-picker">{skills.map(s=><label key={s.id}><input type="checkbox" checked={draft.skills.includes(s.id)} onChange={()=>set('skills',draft.skills.includes(s.id)?draft.skills.filter((id:string)=>id!==s.id):[...draft.skills,s.id])}/><span>{s.thai}<small>{s.name}</small></span></label>)}</div><div className="form-grid"><label>จำนวนผู้เล่น<input type="number" list="builder-player-options" min="1" max="100" value={draft.players} onChange={e=>set('players',Number(e.target.value),true)}/></label><datalist id="builder-player-options">{site.builder.playerOptions.map((n:number)=><option key={n} value={n}/>)}</datalist><label>เวลา (นาที)<input type="number" min="5" value={draft.minutes} onChange={e=>set('minutes',Number(e.target.value),true)}/></label><label className="wide">บริบทผู้เล่นและสิ่งที่ต้องคำนึง<textarea value={draft.context} onChange={e=>set('context',e.target.value)}/></label></div></>}
 {current==='activity'&&<><h2>กิจกรรมสร้างการเรียนรู้ที่มาจากทักษะ</h2><p>สรุปนี้อ่านอย่างเดียว ใช้เป็นฐานก่อนปรับกติกา</p>{draft.skills.map((id:string)=><BuilderActivity key={id} skillId={id}/>)}{draft.packageId&&<p>ชุดต้นแบบ: {packages.find(p=>p.id===draft.packageId)?.name}</p>}</>}
 {current==='rules'&&<><h2>ปรับโครงสร้างและกติกา</h2><label>ชื่อต้นแบบ<input value={draft.title} onChange={e=>set('title',e.target.value)}/></label><h3>CORE — โครงสร้างหลัก</h3><div className="form-grid">{['Conflict','Order','Reward','Ending'].map(group=><label key={group}>{group}<select value={draft.core[group]??''} onChange={e=>set('core',{...draft.core,[group]:e.target.value},true)}><option value="">เลือกโครงสร้าง</option>{cards.filter(c=>c.category===group).map(c=><option key={c.id} value={c.id}>{cardName(c.id)}</option>)}</select></label>)}</div><div className="section-action"><h3>TASTE — กลไกเสริมรสชาติ</h3><button onClick={reroll}><Shuffle size={17}/>เปลี่ยนใบที่ไม่ได้ล็อก</button></div><TastePicker draft={draft} onTaste={ids=>set('taste',ids,true)} onLock={id=>set('locked',{...draft.locked,[id]:!draft.locked[id]})}/><div className="form-grid">{[['roles','บทบาทผู้เล่น'],['turns','ลำดับและจำนวนตา'],['objective','เป้าหมาย'],['ending','เงื่อนไขจบเกม']].filter(([f])=>f!=='roles'||site.builder.optionalSections.roles).map(([field,label])=><label key={field}>{label}<input value={draft[field]} onChange={e=>set(field,e.target.value,true)}/></label>)}<label>จำนวนการ์ด<input type="number" min="1" value={draft.cardCount} onChange={e=>set('cardCount',Number(e.target.value),true)}/></label>{site.builder.optionalSections.customRules&&<label className="wide">กติกาที่กำหนดเอง<textarea rows={5} value={draft.rules} onChange={e=>set('rules',e.target.value,true)}/></label>}{site.builder.optionalSections.debrief&&<label className="wide">คำถามหลังเล่นและสิ่งที่จะสังเกต<textarea value={draft.debrief} onChange={e=>set('debrief',e.target.value)}/></label>}</div></>}
 {current==='review'&&<><h2>{draft.title}</h2><p>{draft.players} คน · {draft.minutes} นาที · {draft.cardCount} การ์ด</p><p>{draft.context}</p><h3>ทักษะและกิจกรรม</h3>{draft.skills.map((id:string)=><p key={id}>{skillName(id)} — {skills.find(s=>s.id===id)?.observe}</p>)}<h3>โครงสร้างและกลไก</h3><p>{[...Object.values(draft.core),...draft.taste].map(id=>cardName(id as string)).filter(Boolean).join(' · ')}</p>{[['roles','บทบาท'],['turns','ตาเล่น'],['objective','เป้าหมาย'],['ending','การจบเกม'],['rules','กติกา'],['debrief','คำถามหลังเล่น']].map(([f,l])=><div key={f}><h3>{l}</h3><p className="preserve-lines">{draft[f]||'ยังไม่กำหนด'}</p></div>)}<p className="condition-note">{draft.analysisReview?'กติกาหรือบริบทเปลี่ยนแล้ว ต้องตรวจข้อวิเคราะห์ทักษะที่รับมาจากชุดเดิมใหม่':'ต้นแบบนี้ต้องทดลองและตรวจพฤติกรรมผู้เล่นก่อนสรุปผลการเรียนรู้'}</p><div className="actions"><button className="primary" onClick={save}><Save/>บันทึกในอุปกรณ์</button><button onClick={exportFile}><Download/>ส่งออก JSON</button><button onClick={()=>window.print()}>พิมพ์ / PDF</button></div></>}
 <div className="builder-actions"><button disabled={step===0} onClick={()=>{setStep(step-1);window.scrollTo(0,0)}}><ArrowLeft/>ก่อนหน้า</button><span>{step+1} / 4{saved?' · บันทึกแล้ว':''}</span>{step<3&&<button className="primary" disabled={!canNext} onClick={()=>{setStep(step+1);window.scrollTo(0,0)}}>ถัดไป<ArrowRight/></button>}</div><p role="status">{status}</p></section></>;
}
