import {useState} from 'react';
import {BookOpen,Waypoints} from 'lucide-react';
import {games,skills,packages,groups,groupNames,groupColors,skillName,url,base,isGameInResearch,relatedGames,skillExamples,packagesForSkill,cleanText,skillColors} from '../lib/model';
import type {Row} from '../lib/model';
import {connectedSkills} from '../lib/catalogue-filter.mjs';
import {GameCover,AwardBadges} from './GameMedia';
import {GameFacts,RankSummary,SkillBadge} from './GameSummary';
import {Pizza,SkillFlow,HatChip,Sources,EvidenceLabel} from './Shared';
function RelatedGame({game,entries}:{game:Row,entries:Row[]}){return <article className="related-game"><GameCover game={game}/><div><h3><a href={url('game',{id:game.id})}>{game.name}</a></h3><p>ทักษะที่เชื่อมโยง:</p><div className="chips">{entries.map(e=><SkillBadge key={e.skill_id} entry={e}/>)}</div></div></article>}
export function GameDetail({id}:{id:string}){const game=games.find(g=>g.id===id);const connected=game?connectedSkills(game):[];const [chosen,setChosen]=useState('');const active=connected.some((s:Row)=>s.skill_id===chosen)?chosen:connected[0]?.skill_id??'';if(!game)return <p>ไม่พบเกมนี้ <a href={url('catalogue')}>กลับคลังเกม</a></p>;
 return <><nav className="breadcrumb" aria-label="เส้นทางหน้า"><a href={url('catalogue')}>คลังเกม</a><span>/</span><span>{game.name}</span></nav><div className="detail-overview"><section className="panel game-hero"><GameCover game={game} variant="hero"/><h1 className="game-title">{game.name}</h1><RankSummary game={game}/><AwardBadges game={game}/><GameFacts game={game}/><h2><BookOpen size={22}/>ภาพรวมเกม</h2><p>{cleanText(game.rules_summary??game.decision??game.action??'ยังไม่มีคำอธิบายเกมที่ตรวจเพียงพอ')}</p>{game.tradeoff&&<p>{cleanText(game.tradeoff)}</p>}<Sources sources={game.sources}/></section><section className="panel skill-map"><h2>แผนที่ 12 ทักษะ</h2><Pizza game={game} selected={active} onSelect={setChosen}/></section></div><section className="game-learning"><h2>เกมนี้เปิดโอกาสให้ฝึกทักษะอย่างไร</h2>{connected.length?<><div className="skill-buttons" role="group" aria-label="ทักษะที่มีบทวิเคราะห์">{connected.map((s:Row)=><button key={s.skill_id} style={{"--skill-color":skillColors[s.skill_id]} as React.CSSProperties} aria-pressed={active===s.skill_id} onClick={()=>setChosen(s.skill_id)}>{skillName(s.skill_id)}{s.status==='C'?' · มีเงื่อนไข':''}</button>)}</div><SkillFlow game={game} skillId={active}/></>:<p className="research-empty">กำลังค้นคว้า — ยังไม่มีทางเชื่อมทักษะที่ทบทวนแล้วสำหรับเกมนี้</p>}</section><h2><Waypoints/>เกมที่เชื่อมโยงกัน</h2><div className="related-list">{relatedGames(game).map(r=><RelatedGame key={r.game.id} game={r.game} entries={r.shared}/>)}</div></>;
}
export function Compare({ids}:{ids:string[]}){const chosen=[...new Set(ids)].map(id=>games.find(g=>g.id===id)).filter(Boolean).slice(0,4) as Row[];if(chosen.length<2)return <p>เลือก 2–4 เกมจาก <a href={url('catalogue')}>คลังเกม</a> เพื่อเปรียบเทียบ</p>;
 const sections:[string,(g:Row)=>React.ReactNode][]=[
 ['ข้อมูลเกม',g=><><GameFacts game={g}/><AwardBadges game={g}/></>],
 ['ทักษะที่เชื่อมโยง',g=><div className="chips">{connectedSkills(g).map((s:Row)=><SkillBadge key={s.skill_id} entry={s}/>)}</div>],
 ['กิจกรรมสร้างการเรียนรู้',g=><>{connectedSkills(g).map((s:Row)=><div key={s.skill_id}><h3>{skillName(s.skill_id)}</h3><p>{cleanText(s.player_action)}</p>{s.status==='C'&&<p className="condition-note">{cleanText(s.conditions)}</p>}</div>)}</>],
 ['กติกาที่ทำให้เกิดกิจกรรม',g=><>{connectedSkills(g).map((s:Row)=><div key={s.skill_id}><h3>{skillName(s.skill_id)}</h3><p>{cleanText(s.bridge?.rule_evidence?.summary_th??g.rules_summary??'ยังไม่มีข้อความกติกาที่ตรวจเพียงพอ')}</p></div>)}</>],
 ['Wizard Hat',g=><>{['CORE','TASTE'].map(section=><div key={section}><h3>{section}</h3><div className="chips">{[...new Set(connectedSkills(g).flatMap((s:Row)=>(s.bridge?.wizard_hat??[]).filter((w:Row)=>w.framework_role===section).map((w:Row)=>w.card_no)))].map((id:any)=><HatChip key={id} id={id}/>)}</div></div>)}</>],
 ['แหล่งอ้างอิง',g=><Sources sources={g.sources}/>]];
 return <><a href={url('catalogue')}>เปลี่ยนเกมที่เลือก</a><div className="comparison-scroll" tabIndex={0} aria-label="ตารางเปรียบเทียบ เลื่อนแนวนอนได้"><table className="comparison-table"><thead><tr><th scope="col">เปรียบเทียบ</th>{chosen.map(g=><th scope="col" key={g.id}><GameCover game={g} variant="compare"/><h2><a href={url('game',{id:g.id})}>{g.name}</a></h2><RankSummary game={g}/>{isGameInResearch(g)&&<span className="research-badge">กำลังค้นคว้า</span>}</th>)}</tr></thead><tbody>{sections.map(([title,render])=><tr key={title}><th scope="row">{title}</th>{chosen.map(g=><td key={g.id} className={isGameInResearch(g)?'in-research':''}>{isGameInResearch(g)&&!['ข้อมูลเกม','แหล่งอ้างอิง'].includes(title)?<p className="muted">ยังไม่มีบทวิเคราะห์ที่ทบทวนแล้ว</p>:render(g)}</td>)}</tr>)}</tbody></table></div></>;
}
export function Skills({id}:{id:string|null}){const skill=skills.find(s=>s.id===id);if(skill){const list=skillExamples(skill.id),packs=packagesForSkill(skill.id);return <><nav className="breadcrumb"><a href={url('skills')}>12 ทักษะ</a><span>/</span><span>{skill.name}</span></nav><h2>{skill.name}</h2><p>{skill.criterion}</p><p>ชวนสังเกต: {skill.observe}</p><p className="reference-note">สิ่งที่ยังไม่พอ: {skill.counter}</p><h2>เกมและเงื่อนไขที่มีข้อมูลกติกา ({list.length})</h2><div className="related-list">{list.map((r:Row)=><article className="skill-example" key={r.game.id}><div className="game-identity"><GameCover game={r.game}/><div><h3><a href={url('game',{id:r.game.id})}>{r.game.name}</a></h3><EvidenceLabel entry={{status:r.status}}/></div></div>{r.status==='C'&&<p className="condition-note">{r.conditions_th}</p>}<p>{cleanText(r.game.skills.find((e:Row)=>e.skill_id===skill.id)?.player_action)}</p><p>{r.applicable_player_counts?.join(', ')} คน</p></article>)}</div>{!list.length&&<p>ยังไม่มีตัวอย่างเกมที่มีหลักฐานเพียงพอ ชุดออกแบบด้านล่างเป็นข้อเสนอสำหรับทดลอง</p>}<h2>ชุดกลไกสำหรับออกแบบ</h2><div className="package-grid">{packs.map(p=><article className="panel" key={p.id}><h3>{p.name}</h3><p>{p.rule_proposal}</p><p>{p.observation}</p><p className="reference-note">{p.limitations_th??'ข้อเสนอ WoL สำหรับทดลอง ยังไม่ใช่ผลทดสอบการเรียนรู้'}</p><a className="button primary" href={url('builder',{package:p.id,skills:skill.id})}>สร้างต้นแบบจากชุดนี้ →</a></article>)}</div><a className="button" href={url('builder',{skills:skill.id})}>เริ่มจากทักษะนี้</a></>}
 return <><section className="panel skills-intro"><img className="skills-art" src={base+"/assets/brand/atlas-skills-v1.png"} alt="จากทักษะ ผ่านกิจกรรมและกติกา สู่เกม" width="1733" height="907"/><h2>ทำไมต้อง 12 Transferable Skills?</h2><p>ทักษะที่นำไปใช้ได้ข้ามวิชาและสถานการณ์ชีวิต ช่วยให้เราคิดแก้ปัญหา ทำงานกับผู้อื่น และจัดการตนเอง กรอบ Life Skills and Citizenship Education ของ UNICEF MENA จัด 12 ทักษะไว้ใน 4 มิติ: เรียนรู้ ลงมือทำ เติบโตเป็นตัวเอง และอยู่ร่วมกับผู้อื่น เพื่อเชื่อมการเรียนรู้กับชีวิตและการทำงาน</p><p>Atlas ใช้กรอบนี้สำรวจว่า <b>กติกาเกมเปิดโอกาสให้ผู้เล่นทำกิจกรรมใด</b> แล้วนำไปออกแบบการเรียนรู้ สีทั้ง 4 กลุ่มใช้ร่วมกันตลอดเว็บ บทวิเคราะห์แสดงโอกาสและเงื่อนไขตามกติกา ยังไม่ใช่ผลวัดพัฒนาการ</p><a className="intro-source" href="https://www.unicef.org/mena/reports/reimagining-life-skills-and-citizenship-education-middle-east-and-north-africa" target="_blank" rel="noreferrer">อ่านกรอบแนวคิดต้นทาง UNICEF ↗</a></section>{groups.map((group,i)=><section key={group} className="skill-group"><h2><i style={{background:groupColors[i]}}/>{groupNames[i]} <small>{group}</small></h2><div className="skill-grid">{skills.filter(s=>s.dimension===group).map(s=><article className="panel" key={s.id} style={{borderTop:`4px solid ${groupColors[i]}`}}><h3><a href={url('skill',{id:s.id})}>{s.name}</a></h3><p>{s.criterion}</p><div className="skill-overview-examples">{skillExamples(s.id,3).map((r:Row)=><div className="mini-game" key={r.game.id}><GameCover game={r.game}/><a href={url('game',{id:r.game.id})}>{r.game.name}{r.status==='C'?' *':''}</a></div>)}</div>{!skillExamples(s.id,1).length&&<p className="muted">ยังไม่มีตัวอย่างที่มีหลักฐานเพียงพอ</p>}</article>)}</div></section>)}</>;
}
