import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {staticMetadataAdapter} from './lib/static-metadata.mjs';
import {staticImageAdapter} from './lib/static-images.mjs';
const app=path.resolve('..'), kb=path.resolve('../../../../03_Documents/04_Knowledge_Base/05_Research_Library');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const shelf=path.join(kb,'learning-game-atlas/data');
const preview=read(path.join(app,'preview-data.json'));
const catalogue=fs.existsSync(path.join(shelf,'production-catalogue.json'))?read(path.join(shelf,'production-catalogue.json')):read(path.join(kb,'strategy-card-games/data/games.json'));
const wh=fs.existsSync(path.join(shelf,'wizard-hat-production.json'))?read(path.join(shelf,'wizard-hat-production.json')):read(path.join(shelf,'wizard-hat.json'));
const optional=n=>fs.existsSync(path.join(shelf,n))?read(path.join(shelf,n)):null;
// Curated edition-scoped facts overlay; retain original register and supplemental awards.
const facts=optional('reviewed-game-facts.json');
const overlay=new Map((facts?.records??[]).map(r=>[r.game_id,r]));
const applyFacts=g=>{const f=overlay.get(g.game_id??g.id);if(!f)return g;const merged={...g,...f,source_provenance:[...new Map([...(g.source_provenance??g.sources??[]),...f.source_provenance].map(source=>[JSON.stringify([source.url,source.locator]),source])).values()],reviewed_fact_source:'reviewed-game-facts.json',original_fact_snapshot:{players:g.players,publisher_play_duration_minutes:g.publisher_play_duration_minutes,medium:g.medium,format:g.format,genres:g.genres}};delete merged.record_revision_sha256;merged.record_revision_sha256=crypto.createHash('sha256').update(JSON.stringify(merged)).digest('hex');return merged;};
if(catalogue.records)catalogue.records=catalogue.records.map(applyFacts);else catalogue.games=catalogue.games.map(applyFacts);
const supplement=optional('sdj-supplemental-games.json');if(supplement)supplement.records=supplement.records.map(applyFacts);
const decisions=optional('bgg-owner-identity-decisions.json'), staged=optional('bgg-metadata-staging.json');
if(!decisions||!staged)throw Error('Selected static identity inputs are required');
const excluded=new Set(decisions.records.filter(r=>r.action==='exclude').map(r=>r.game_id));
const selectionReview=optional('bgg-owner-selection-review.json');
const blockedJoins=new Set((selectionReview?.records??[]).filter(r=>r.public_join_allowed===false).map(r=>r.game_id));
const stagedById=new Map(staged.records.map(r=>[r.game_id,r]));
const references=g=>{const r=stagedById.get(g.game_id??g.id);if(!r)throw Error('Missing selected identity row');return {...g,bgg_reference:{bgg_id:blockedJoins.has(g.game_id??g.id)?null:r.bgg_id,game_url:blockedJoins.has(g.game_id??g.id)?null:r.bgg_url,identity_conflict:blockedJoins.has(g.game_id??g.id),identity_status:r.bgg_identity_status,selection_basis:r.identity_selection_basis,learning_identity_recheck_required:r.learning_identity_recheck_required}}};
if(catalogue.records)catalogue.records=catalogue.records.filter(g=>!excluded.has(g.game_id)).map(references);else catalogue.games=catalogue.games.filter(g=>!excluded.has(g.id)).map(references);
if(supplement)supplement.records=supplement.records.filter(g=>!excluded.has(g.game_id)).map(references);

const staticContract=optional('games-web-static.json'), reviewedIdentities=optional('bgg-reviewed-identity-map.json');
if(!staticContract||!reviewedIdentities)throw Error('Static metadata inputs are required');
const metadata=staticMetadataAdapter(staticContract,reviewedIdentities);
metadata.assertCoverage([...(catalogue.records??catalogue.games),...(supplement?.records??[])]);
const imageRegister=optional('game-image-register.json');
if(!imageRegister)throw Error('Canonical image register is required');
const images=staticImageAdapter(imageRegister,reviewedIdentities);
const applyMetadata=g=>{const merged=images.apply(metadata.apply(g));delete merged.record_revision_sha256;merged.record_revision_sha256=crypto.createHash("sha256").update(JSON.stringify(merged)).digest("hex");return merged;};
if(catalogue.records)catalogue.records=catalogue.records.map(applyMetadata);else catalogue.games=catalogue.games.map(applyMetadata);
if(supplement)supplement.records=supplement.records.map(applyMetadata);
fs.mkdirSync('src/data',{recursive:true});fs.mkdirSync('public/assets',{recursive:true});
for(const n of ['fonts','wh'])fs.cpSync(path.join(app,'assets',n),path.join('public/assets',n),{recursive:true});
const data={catalogue,wh,supplement,skills:preview.skills,packages:preview.packages,annotations:preview.games,activities:optional('learning-activities.json'),bridges:optional('reviewed-skill-bridges.json'),flows:optional('reviewed-learning-flows.json'),imported_at:'2026-10-04',digest:crypto.createHash('sha256').update(JSON.stringify({catalogue,wh,supplement,facts,staticContract,reviewedIdentities,imageRegister,activities:optional('learning-activities.json'),bridges:optional('reviewed-skill-bridges.json'),flows:optional('reviewed-learning-flows.json'),skills:preview.skills,packages:preview.packages})).digest('hex')};
fs.writeFileSync('src/data/atlas.json',JSON.stringify(data,null,2));
const pick=(r,keys)=>Object.fromEntries(keys.filter(k=>r[k]!==undefined).map(k=>[k,r[k]]));
const lean={...data,flows:data.flows?{game_count:data.flows.game_count,flow_count:data.flows.flow_count,flows:data.flows.flows.map(f=>pick(f,['bridge_id','skill_definition_th','edition_scope','debrief_question_th','debrief_provenance','source_locator']))}:null,catalogue:{records:(catalogue.records??catalogue.games).map(g=>({...pick(g,['game_id','id','name','name_th','aliases','publisher','players','player_counts','publisher_play_duration_minutes','official_play_min','official_play_max','medium','format','format_detail','genres','player_relationship','edition_scope','reviewed_fact_source','mechanisms','design_analysis','source_provenance','sources','bgg','bgg_reference','bgg_ranking_snapshot','bgg_metadata_snapshot','external_cover','atlas_annotation','record_revision_sha256']),transferable_skills:{skill_map:(g.transferable_skills?.skill_map??[]).filter(s=>!['U','X'].includes(s.status)).map(s=>pick(s,['skill_id','status','player_action','constraint','conditions','observable','counter_signal','applicable_player_counts','source_locators']))}}))},bridges:data.bridges?{games:data.bridges.games.map(g=>({...pick(g,['game_id','name','rule_evidence','wizard_hat','timing','edition_scope','applicable_player_counts']),skills:g.skills.map(s=>pick(s,['skill_id','status','status_label_th','reason_th','bridge_id']))})),bridges:data.bridges.bridges.map(b=>({...pick(b,['bridge_id','game_id','skill_id','activity_id','status','status_label_th','activity_th','required_action_th','observable_behaviour_th','counter_signal_th','wizard_hat','wizard_hat_gap_th','applicable_player_counts','role_th','conditions_th','observation_method_th']),rule_evidence:JSON.stringify(b.rule_evidence)===JSON.stringify(data.bridges.games.find(g=>g.game_id===b.game_id)?.rule_evidence)?null:b.rule_evidence})),related_games_by_skill:data.bridges.related_games_by_skill}:null,annotations:[]};
fs.writeFileSync('src/data/public-atlas.json',JSON.stringify(lean));
console.log('Imported',catalogue.games?.length??catalogue.records?.length,'games;',wh.cards?.length,'cards; activities',!!data.activities,'bridges',!!data.bridges);
