import fs from 'node:fs';
let p='src/components/App.tsx',s=fs.readFileSync(p,'utf8');
s=s.replace('groupNames,groupColors}', 'groupNames,groupColors,skillExamples,packagesForSkill}');
s=s.replace("[type,setType]=useState(''),[view", "[type,setType]=useState(''),[maxMinutes,setMaxMinutes]=useState(''),[view");
s=s.replace("(!players||!s.applicable_player_counts||Array.from(s.applicable_player_counts).map(String).includes(players))", "(!players||(Array.isArray(s.applicable_player_counts)&&s.applicable_player_counts.map(String).includes(players)))");
s=s.replace("(!type||g.format.includes(type)||g.medium===type));", "(!type||g.format.includes(type)||g.medium===type)&&(!maxMinutes||(g.play_max!==null&&g.play_max<=Number(maxMinutes))));");
s=s.replace("setType('');setPage(1)","setType('');setMaxMinutes('');setPage(1)");
s=s.replace("</select></label><button onClick={()=>{setQ('')", "</select></label><label>เวลาผู้ผลิตระบุ<select aria-label=\"เวลาผู้ผลิตระบุ\" value={maxMinutes} onChange={e=>{setMaxMinutes(e.target.value);setPage(1)}}><option value=\"\">ทุกเวลา</option>{[15,30,45,60].map(n=><option key={n} value={n}>ไม่เกิน {n} นาที</option>)}</select></label><button onClick={()=>{setQ('')");
s=s.replace("} นาที`:'เวลายังไม่ทราบ'", "} นาที · ผู้ผลิตระบุ`:'เวลายังไม่ทราบ'");
s=s.replace("const list=games.filter(g=>supported(g).some((e:Row)=>e.skill_id===s.id)).slice(0,10),packs=packages.filter(p=>p.skills.includes(s.id));", "const list=skillExamples(s.id),packs=packagesForSkill(s.id);");
s=s.replace('เกมที่มีข้อมูลกติกาสนับสนุน ({list.length})','เกมและเงื่อนไขที่มีข้อมูลกติกา ({list.length})');
s=s.replace("{list.map(g=><article key={g.id}><a href={url('game',{id:g.id})}>{g.name}</a><p>{cleanText(g.skills.find((e:Row)=>e.skill_id===s.id)?.player_action)}</p></article>)}", "{list.map((r:Row)=><article key={r.game.id}><a href={url('game',{id:r.game.id})}>{r.game.name}</a><EvidenceLabel entry={{status:r.status}}/><p>{cleanText(r.game.skills.find((e:Row)=>e.skill_id===s.id)?.player_action)}</p><p className={r.status==='C'?'condition-note':'muted'}>{r.applicable_player_counts?.join(', ')} คน · {r.conditions_th}</p></article>)}");
s=s.replace("{games.filter(g=>supported(g).some((e:Row)=>e.skill_id===s.id)).slice(0,3).map(g=><a key={g.id} href={url('game',{id:g.id})}>{g.name}</a>)}", "{skillExamples(s.id,3).map((r:Row)=><span key={r.game.id}><a href={url('game',{id:r.game.id})}>{r.game.name}</a>{r.status==='C'&&<small> · มีเงื่อนไข</small>}</span>)}");
s=s.replace("{!games.some(g=>supported(g).some((e:Row)=>e.skill_id===s.id))&&", "{!skillExamples(s.id,1).length&&");
s=s.replace("bgg.rating??'ยังไม่ทราบ'", "bgg.average_rating??bgg.rating??'ยังไม่ทราบ'");
s=s.replace("ข้อมูล ณ {bgg.as_of??bgg.asof??'ยังไม่ทราบ'}</small>", "วันของสถิติ {bgg.as_of??bgg.asof??'ยังไม่ทราบ'}{bgg.retrieved_on&&` · ดึง snapshot เมื่อ ${bgg.retrieved_on}`}</small>{bgg.source_url&&<a href={bgg.source_url} target=\"_blank\" rel=\"noreferrer\">ข้อมูล BGG ต้นทาง</a>}{bgg.observation_note&&<small>ตัวเลขจากภาพข้อมูลที่ตรวจ ไม่ใช่อันดับสด · จำนวนผู้ให้คะแนนแบบปัดเศษไม่ใช้เป็นจำนวนที่แน่นอน</small>}");
fs.writeFileSync(p,s);
p='src/components/Builder.tsx';s=fs.readFileSync(p,'utf8');
s=s.replace("taste:p?.cards?.map(String)??(params.get('card')?[params.get('card')]:[])", "taste:(p?.cards?.map(String)??(params.get('card')?[params.get('card')]:[])).filter((id:string)=>cards.find(c=>c.id===id)?.section==='TASTE')");
s=s.replace("core:{} as Record<string,string>", "core:Object.fromEntries((p?.cards?.map(String)??(params.get('card')?[params.get('card')]:[])).map((id:string)=>cards.find(c=>c.id===id)).filter((c:Row|undefined)=>c?.section==='CORE').map((c:Row)=>[c.category,c.id])) as Record<string,string>");
s=s.replace("<p>{cleanText(r.activity??r.behaviour??r.summary??r.learning_activity)}</p>", "<div><h4>{r.wol_activity?.title_th}</h4><p>{r.wol_activity?.action_th??cleanText(r.activity??r.behaviour??r.summary??r.learning_activity)}</p><ol>{r.wol_activity?.steps_th?.map((t:string)=><li key={t}>{t}</li>)}</ol><p>{r.wol_activity?.facilitation_note_th}</p></div>");
s=s.replace('<label className="wide">กติกาที่กำหนดเอง', '{site.builder.optionalSections.customRules&&<label className="wide">กติกาที่กำหนดเอง');
s=s.replace("onChange={e=>set('rules',e.target.value,true)}/></label>{site.builder.optionalSections.debrief", "onChange={e=>set('rules',e.target.value,true)}/></label>}{site.builder.optionalSections.debrief");
fs.writeFileSync(p,s);
